### PR TITLE
Fix mac-cleanup formula

### PR DESCRIPTION
**Pull request by deydoux**

### CODE REVIEW

**Review by fwartner — APPROVED** [review]
All good so far. The action within the main repository needs to be updated for that as well.

**Comment by deydoux** [comment]
I haven't tested it on a M1 Mac but it should theoretically work

**Comment by Fudoshiki** [comment]
merge?

**Comment by deydoux** [comment]
The Homebrew TAP is ready but mac-cleanup/mac-cleanup repository isn’t

**Pull request merged**
